"""Цветовые схемы интерфейса.

Каждая тема — плоский словарь токенов. Ключи name_en/name_ru задают подпись
в настройках, остальные — цвета, которые виджеты читают как T["ACCENT"].
"""

THEMES = {
    "cyber": {
        "name_en": "Cyber Dark",
        "name_ru": "Кибер Тёмный",
        "BG_DARK":      "#0a0c10",
        "BG_CARD":      "#0f1318",
        "BG_PANEL":     "#131820",
        "BORDER":       "#1e2a38",
        "ACCENT":       "#00d4ff",
        "ACCENT2":      "#ff3a5c",
        "ACCENT3":      "#ffc94a",
        "TEXT_PRIMARY": "#e8edf5",
        "TEXT_DIM":     "#5a6a80",
        "TEXT_MUTED":   "#2e3d52",
        "SCROLLBAR_BG": "#050708",
        "GLOW":         "#003d4d",
    },
    "blood": {
        "name_en": "Blood Red",
        "name_ru": "Кровавый",
        "BG_DARK":      "#0d0608",
        "BG_CARD":      "#130a0c",
        "BG_PANEL":     "#1a0c0f",
        "BORDER":       "#3a1a20",
        "ACCENT":       "#ff3a5c",
        "ACCENT2":      "#ff8c00",
        "ACCENT3":      "#ffc94a",
        "TEXT_PRIMARY": "#f5e8ea",
        "TEXT_DIM":     "#7a4a52",
        "TEXT_MUTED":   "#3d1e24",
        "SCROLLBAR_BG": "#080304",
        "GLOW":         "#4d0010",
    },
    "matrix": {
        "name_en": "Matrix Green",
        "name_ru": "Матрица",
        "BG_DARK":      "#010d01",
        "BG_CARD":      "#041204",
        "BG_PANEL":     "#061806",
        "BORDER":       "#0f3a0f",
        "ACCENT":       "#00ff41",
        "ACCENT2":      "#39ff14",
        "ACCENT3":      "#7fff00",
        "TEXT_PRIMARY": "#ccffcc",
        "TEXT_DIM":     "#2a6a2a",
        "TEXT_MUTED":   "#0f3a0f",
        "SCROLLBAR_BG": "#010801",
        "GLOW":         "#003300",
    },
    "gold": {
        "name_en": "Ancient Gold",
        "name_ru": "Золото Древних",
        "BG_DARK":      "#0d0a04",
        "BG_CARD":      "#130f06",
        "BG_PANEL":     "#1a1408",
        "BORDER":       "#3a2e10",
        "ACCENT":       "#ffc94a",
        "ACCENT2":      "#ff8c00",
        "ACCENT3":      "#00d4ff",
        "TEXT_PRIMARY": "#f5eecc",
        "TEXT_DIM":     "#7a6a30",
        "TEXT_MUTED":   "#3d3418",
        "SCROLLBAR_BG": "#080600",
        "GLOW":         "#4d3a00",
    },
    "ghost": {
        "name_en": "Ghost White",
        "name_ru": "Призрак",
        "BG_DARK":      "#f0f2f5",
        "BG_CARD":      "#e8eaed",
        "BG_PANEL":     "#dde0e5",
        "BORDER":       "#b0bac8",
        "ACCENT":       "#0066cc",
        "ACCENT2":      "#cc0033",
        "ACCENT3":      "#cc7700",
        "TEXT_PRIMARY": "#0a0c10",
        "TEXT_DIM":     "#5a6a80",
        "TEXT_MUTED":   "#8899aa",
        "SCROLLBAR_BG": "#c8cdd5",
        "GLOW":         "#cce5ff",
    },
}
